# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'master'
    schedule:
      interval: 'monthly'
    assignees:
      - 'derogab'
    labels:
      - 'dependencies'
  
  # Maintain dependencies for Node NPM
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'master'
    schedule:
      interval: 'monthly'
    assignees:
      - 'derogab'
    labels:
      - 'dependencies'
